name: Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Build the project
        run: make

      - name: Project Completed
        run: echo "Test Completed"
